pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                script {
                    sh 'docker build . -t mini-project'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    sh 'docker run --rm mini-project npm test'
                }
            }
        }

        stage('Approval') {
            steps {
                script {
                    // Assuming you want automatic approval if the previous stages were successful
                    // You can customize this condition based on your requirements
                    if (currentBuild.resultIsBetterOrEqualTo('SUCCESS')) {
                        echo 'Automatic approval - Build and Test stages passed'
                    } else {
                        error 'Build or Test stages failed. Manual approval required.'
                    }
                }
            }
        }

        stage('Deploy') {
            steps {
                script {
                    sh 'docker stop mini-project || true'
                    sh 'docker rm mini-project || true'
                    sh 'docker run -d --name mini-project1 -p 5000:5000 mini-project1'
                }
            }
        }

        stage('Push to Registry') {
            steps {
                script {
                    sh 'echo "Aman*9261" | docker login -u "amanlaxkar" --password-stdin'
                    sh 'docker push amanlaxkar/appimage:mini-project'
                }
            }
        }
    }
}
